language: ruby
rvm:
  - ruby-head
  - 2.0
  - 1.9.3
  - jruby-head
  - jruby-19mode # JRuby in 1.9 mode

env:
  COVERAGE=1

branches:
  only:
    - master

source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcnBQVkZ0UjQ2RVh2cnpUaUdxRW9oZks4V2xMM3hKQ01EaU9kaXAxY2ZXdWpIV0pZCnhsZXhHRGM4Qlg0RXNlWWp1dXR2NWJ5V2JqY1pZZ3Z6TmQzV3RGNlVnQ21Od0MzSk9xcnA5ZE9XVzRMemxVUkEKZ3FIa2pyam5HcDA2ZWxINEMrYmRjZ0xJbmRlZWxBam92L1FYaWh2d3JmVlhtNnQ3OTY0alZiQnBtSFpqTHoybQpoZVhZelRrK3JBQldUdjMwSWxwMVRROUdQVUJrOGdlOWFSMnBTYTNoTTU3UnRrOTFQUXU4NGdWSGVUejllTE01CkV6ZTRmMVV2YzNYN2c1OVdLaGhoSkM1UVVKQ0RYa3NzTnhrbjZmY05lYWdQWHZkU1ljSSs5cXVDeWZqSjJSN2UKc1NwajVldFpKcFN2bjNqWkRzSG1MdUtkVldwMWFPQXVRd2lFa3dJREFRQUJBb0lCQUFSZkRVSGlGaGp5ejFxYQp2MktkVUc5eU1ZY3RkcWpFV2MxczFPQUlxcTAxU2NOTm1CMTNTcWJwa3lZc0RxQUp2REZNL2VOSndwYUY2S3ZNCjBzMHhmZFBNWG5tTEVOS1VFdXJXSnIrU0NiekczYVNLTGZkWGFHcXVkSkwxQnViVE1KdlRydzNReGdjMXcvRysKKzF6N0ZxL05uVXd0ellESFhYWkpOUGRMVUltUnVybEZoVE12UktxMWJrTzNyMEpGWEU0UFNJVWtnVmhxUHM5SwpWTUJuMGxzckJadkhNKzhQUnBCUFpNQ1NqY2J6eDFnSFBGb0FuRkdaQzZEbHlpZDRXdDVjSnZBakdKU29pOHZ4CmZhR0R2cDVwREZTZkh0ajZyZXdmVVVnbW5KVWQzMW10THJqUmNMa2xhRktSSGNEekxUdFZwQjcvSWFsbzU2akoKSExZUHlxRUNnWUVBMTVLTEIyWXVrNm4rWXQ2aVBady9ZNDhUVVlJOU5EOGdjSEFKaTREbU1jSndoOVpwRnNZKwpPQ0hFcDdZOFFpZkhwSDVEcDlhdFk5QmlJNm9melllYlBKWG9kUlhyejNGSisxc21jTjFRaWZOWnJseDRxb3lmCnUvcXNETnQ1QzUxVTUyTjVzMEY3dWRySFVhcDdBRFlXZVdUYUtHcFhMSlQ0ZU9HSmVDbXNoeU1DZ1lFQXoxRW4Kak1MNk4rR0pwTjNCZVVWS1FNcmhCaFhha3dUbGt6d1U5dnF4QjYwVzJmRDVQd2ZuTFVKSThldDI2TERZWE9pUApwUUw3T2ZsMk5YS3dweWhsdEdDMEFubVZpbTAzeTh3SG9EU1l0QmR0WFB0RElnbDhHNER5R0pyUzRLeWxyd3lTCml4RE90MTVGQjFVdjhZdmZKYlVBVVk3L0YyOFVYOHRrTkw3MG05RUNnWUVBaVJiVFBUQlpIR1MxdHBCWVlvL1QKcSsrWDNIVFRrVDgzMU9rYTJORnZFbVBSaGtEdThhRytmWm5UNHNlOFNHSGR6eGpRMDVKdEQ1VzhZMnZUNzdOMgpJREJBOVB5c3ltNEVHMG5iQjFsbTEyT2ZPNGZvNEtTdkRDOGNiTXpCaklaUU1Sb01rZGRwNUVaaURPZzZjbWJ6CklkM2w4bCsxOGs4R09IRk5KOUp3dWpzQ2dZQU9JeFdVVnJOalhpRFp1amw0UUk1WXJyejdnai8rYUlZVExUU3MKeHRtTmtYTU9kNDAzakIxcWk2dVh1NXZITUZBQXZlY1Z0SWRYSTdpNDJsSkxnOGl6clNoNVJyczR6a3ZRdk9BRQpQN0h1RGU3cU9VUVJyUjNtYmp1VUMvSzNXVzZPNmtlUDdoeDZpcFlnY3VHckVnT3NlWlJFKzRCUG84WjY1YzYyCmZoTUdFUUtCZ1FEV1Zsb0RkeFRweng5Q25GMkpoZlRjNU0wTERwem96RmZ3RjZmMHZjOUVBQTBxUzV4WTM0TU0KN3o3bk85NGNzQlZ6VVNWWG55WDVDS1VjS09IdnFZV1c2Q01XL240VzVnOXFQR25ZOXpycmw0ejRsU01SejNYKwp3MExqVGlYSEZwVFBJVldWcDVpNlZNOW9RWENSOVBaM2dKMDFHT0hoY2c2UUcxQkd0U3BFSGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

before_script:
    - bundle install

script:
    - bundle exec rake test 
